export const selectors = {
  todoList: document.querySelector('.table'),
  addTodoForm: document.querySelector('.todo-form'),
  nameInput: document.querySelector('#name'),
  contentInput: document.querySelector('#content'),
  categoryInput: document.querySelector('#category'),
  todosItems: document.querySelector('.todos-items'),
  addTodoModal: document.querySelector('.modal'),
  openAddTodoButton: document.querySelector('.open-modal'),
  closeAddTodoButton: document.querySelector('.close-modal'),
  categoriesList: document.querySelector('.categories-table'),
  archivedTodosList: document.querySelector('.archived-table'),
  archivedModal: document.querySelector('.archived-modal'),
  openArchivedButton: document.querySelector('.open-archived-modal'),
  closeArchivedButton: document.querySelector('.close-archived-modal'),
};
